"""dono em livros

Revision ID: 79cbc6acad0d
Revises: df904534ea10
Create Date: 2026-09-17 20:50:36.414294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cbc6acad0d'
down_revision: Union[str, Sequence[str], None] = 'df904534ea10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A coluna e' nullable porque os livros que JA' ESTAO no banco nao tem
    # dono para receber -- eles foram cadastrados quando o acervo era de
    # todos. Eles ficam com dono_id nulo e, a partir daqui, ninguem os ve':
    # a listagem filtra pelo dono. Quem tem um banco assim da' um dono a eles
    # pelo cliente de banco (UPDATE livros SET dono_id = 1) ou apaga.
    #
    # A chave estrangeira leva NOME (fk_livros_dono) porque o SQLite, em
    # migracao, so' cria constraint com nome -- e o modo batch recria a
    # tabela por baixo dos panos para conseguir cria-la.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_livros_dono', 'usuarios', ['dono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.drop_constraint('fk_livros_dono', type_='foreignkey')
        batch_op.drop_column('dono_id')

    # ### end Alembic commands ###
