"""tipo_leitor e devolver_ate em emprestimos

Revision ID: df904534ea10
Revises: 1ee353fc967a
Create Date: 2026-09-17 13:53:22.361799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df904534ea10'
down_revision: Union[str, Sequence[str], None] = '1ee353fc967a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # O server_default e' o que preenche os emprestimos que ja' existem: eles
    # seguiam a regra unica de antes, cujo limite de 3 e' o do aluno. A data
    # fica vazia -- ninguem calculou prazo para eles.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_leitor', sa.String(length=20), server_default='aluno', nullable=False))
        batch_op.add_column(sa.Column('devolver_ate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.drop_column('devolver_ate')
        batch_op.drop_column('tipo_leitor')

    # ### end Alembic commands ###
